### ISSUE TITLE
Use environment variable to hold secrets

### ISSUE THREAD

**Issue by arpat** [AcornHack/Acorn-Connect-Academy#3]
db.js

```
// var mongoose = require('mongoose');
// mongoose.connect('URI'); //message me if you want the URI.

var mongoose = require('mongoose');
var dburi = process.env._DATABASE_URI
mongoose.connect(dburi);
```

...then set the URI as a shell/bash env var:

`export _DATABASE_URI="U:P@ds033956.mlab.com:33956/acorn"`

**Comment by ApCoder123** [comment]
@arpat I've changed the code, but I can't seem to set the env variables. I have a .env file with the var in it and a bash script that looks like this:
```
#!/bin/bash
while read line; do export "$line";
done <source .env 
```
But it doesn't seem to be setting. 
`export _DATABASE_URI="U:P@ds033956.mlab.com:33956/acorn"` doesn't work on windows, so I tried `SET _DATABASE_URI="uri"` but when running the node app, it still can't connect

**Comment by ApCoder123** [comment]
Hmm, I tried to connect using the original method but it still fails to connect. Must be a db issue. I'll check it out
```

events.js:141
      throw er; // Unhandled 'error' event
      ^
 MongoError: failed to connect to server [tions:27017] on first connect [MongoError: getaddrinfo ENOTFOUND tions tions:27017]
    at null.<anonymous> (C:\Users\Arun\WebstormProjects\Acorn-Connect\node_modules\mongodb-core\lib\topologies\server.js:328:35)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at null.<anonymous> (C:\Users\Arun\WebstormProjects\Acorn-Connect\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at emit (events.js:172:7)
    at Socket.<anonymous> (C:\Users\Arun\WebstormProjects\Acorn-Connect\node_modules\mongodb-core\lib\connection\connection.js:177:49)
    at Socket.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at connectErrorNT (net.js:1012:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by ApCoder123** [comment]
Nevermind. Fixed it. It was a db issue.
To set the environment variable:
Windows: `SET _DATABASE_URI=uri` and then `node server.js`
Linux: `export _DATABASE_URI=uri` and then `node server.js`
